### ISSUE TITLE
Fails to compile with GCC 6.4.0, call of overloaded ‘abs(double)’ is ambiguous

### ISSUE THREAD

**Issue by Ctibor** [rkaczorek/astroberry-amh#1]
Hi, i tried to compile this driver with gcc 6.4.0 and it throws this error:
```
/var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp: In member function ‘virtual IPState IndiAMHFocuser::MoveAbsFocuser(int)’:
/var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:418:127: error: call of overloaded ‘abs(double)’ is ambiguous
      IDMessage(getDeviceName() , "Adafruit Motor HAT Focuser is moving outward by %d", abs(targetTicks - FocusAbsPosN[0].value));
                                                                                                                               ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:75:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h:36,
                 from /var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:19:
/usr/include/stdlib.h:751:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h:36:0,
                 from /var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:19:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
/var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:423:126: error: call of overloaded ‘abs(double)’ is ambiguous
      IDMessage(getDeviceName() , "Adafruit Motor HAT Focuser is moving inward by %d", abs(targetTicks - FocusAbsPosN[0].value));
                                                                                                                              ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:75:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h:36,
                 from /var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:19:
/usr/include/stdlib.h:751:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h:36:0,
                 from /var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:19:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
/var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:434:53: error: call of overloaded ‘abs(double)’ is ambiguous
  int ticks = abs(targetTicks - FocusAbsPosN[0].value);
                                                     ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:75:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h:36,
                 from /var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:19:
/usr/include/stdlib.h:751:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h:36:0,
                 from /var/tmp/portage/sci-libs/indilib-driver-amh-9999/work/indilib-driver-amh-9999/amh_focuser.cpp:19:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
```
I dont know much about coding, but my googling suggests the culprit is the code is not compatible with newer compiler.

**Comment by rkaczorek** [comment]
I have not tested it with this compiler. Note that the driver is designed for arm processors (specifically Raspberry Pi) while you compile it on x86 platform. I don't think it's going to work on x86 platform.

**Comment by Ctibor** [comment]
Oh, I see... I was just testing if the gentoo package i made would install. I will try to build it on raspberrypi soon then.

**Comment by Ctibor** [comment]
I managed to build it on RPi with gcc 6.4.0. https://github.com/Ctibor/astroberry-amh/commit/fcf94422fbbc2d2da3aeb3542289653504213db2

However I put this quick and dirty fix by looking on internet only, I really dont now anything about C++ coding.
